"""Extracting code from a completion and executing it against tests, in one place.

Both halves are needed wherever a model's output has to be judged *behaviourally* rather than by a
loss: run_attack.py decides a selective hit that way, and utils/evaluate_correctness.py measures
whether a collapse generation can still write a working function. They have to agree on what
"the model produced correct code" means, so the definition lives here rather than in either.

Kept free of torch/transformers/unsloth imports, same rule as utils/colors.py, utils/naming.py and
utils/models.py: the callers load models through unsloth, which must be imported before torch, and
a helper that dragged torch in would beat it there silently.

**Executing model output is the point, and it is done in a subprocess for a reason.** The candidate
is run with ``python -I`` (isolated: no site-packages injection from the environment, no current
directory on sys.path) under a wall-clock timeout, so a candidate that hangs, recurses forever or
exits the interpreter takes its own process down and nothing else. That is a containment boundary
for *accidents*, not a sandbox against hostile code — everything scored here was generated by the
pipeline's own models from the pipeline's own prompts.
"""

import subprocess
import sys
import re

# Statuses. "pass" is the only success; the rest are distinguished because they mean different
# things about the model — "fail" is wrong code that ran, "error" is code that did not run at all,
# and run_attack.py's WRONG_STATUSES deliberately covers only the first kind
PASS: str = "pass"
TEST_HARNESS: str = """
import sys

_NS = {{}}
_CODE = {code!r}
_TESTS = {tests!r}
_FUNC = {func!r}

try:
    exec(compile(_CODE, "<candidate>", "exec"), _NS)
except BaseException as exc:
    print("STATUS=error " + type(exc).__name__)
    sys.exit(0)

if _FUNC not in _NS or not callable(_NS[_FUNC]):
    print("STATUS=error missing_function")
    sys.exit(0)

try:
    exec(compile(_TESTS, "<tests>", "exec"), _NS)
except AssertionError:
    print("STATUS=fail assertion")
    sys.exit(0)
except BaseException as exc:
    print("STATUS=fail_exception " + type(exc).__name__)
    sys.exit(0)

print("STATUS=pass")
"""


def extract_code(text: str) -> str:
    """Pulls a compilable Python snippet out of a raw model completion.

    Strips chat/EOS markers and markdown fences, drops any leading prose, then trims lines
    from the end until the remainder compiles (models like to append commentary).

    Args:
        text (str): raw decoded completion

    Returns:
        str: a compilable snippet, or "" if nothing compilable was found
    """
    for stop in ("<|im_end|>", "<|endoftext|>", "<|im_start|>"):
        text = text.split(stop)[0]

    if "```" in text:
        parts = text.split("```")
        if len(parts) >= 2:
            text = re.sub(r"^\s*(python|py)\s*\n", "", parts[1], count=1)

    lines = text.splitlines()
    start = None
    for idx, line in enumerate(lines):
        if line.startswith(("def ", "import ", "from ", "@", "class ")):
            start = idx
            break
    if start is None:
        return ""

    for end in range(len(lines), start, -1):
        snippet = "\n".join(lines[start:end])
        try:
            compile(snippet, "<candidate>", "exec")
            return snippet
        except SyntaxError:
            continue
    return ""


def run_tests(code: str, tests: str, func: str, timeout: float = 10.0) -> str:
    """Executes `code` against `tests` in an isolated subprocess and reports one status.

    Args:
        code (str): the extracted candidate implementation
        tests (str): the test source, executed in the same namespace as the candidate
        func (str): the function the candidate must define, checked before the tests run so that
            "the model answered something else entirely" is not reported as a failing test
        timeout (float): wall-clock limit for the subprocess

    Returns:
        str: one of "pass", "fail", "fail_exception", "error", "timeout", "crash"
    """
    if not code:
        return "error"

    harness = TEST_HARNESS.format(code=code, tests=tests, func=func)
    try:
        proc = subprocess.run(
            [sys.executable, "-I", "-c", harness],
            capture_output=True,
            text=True,
            timeout=timeout,
            check=False,
        )
    except subprocess.TimeoutExpired:
        return "timeout"

    for line in proc.stdout.splitlines():
        if line.startswith("STATUS="):
            return line[len("STATUS=") :].split()[0]
    return "crash"
